name: Calculate Polynomials

on:
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Execute script
        run: node V1.js
